/**
 * Species library for the near-field generator. Every entry is a TYPICAL APPROXIMATION: heights, spreads, colours and
 * phenology windows are representative values for a genus/growth form, not measurements of any real individual or
 * place. Fruit/flower months use the northern-hemisphere calendar; the generator mirrors them (+6 months) south of the
 * equator. Biome weights are relative frequencies within a biome, not absolute densities.
 */
import type { Biome } from '@/world/climate/biome';
import { BIOME_INFO } from '@/world/climate/biome';
import type { Rng } from '@/util/hash';
import type { Species, SpeciesKind } from './types';

const ALL_MONTHS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

/** Master species table (≥ 45 entries). Ids are stable identifiers used by Placement.species. */
export const SPECIES: readonly Species[] = [
  // ---- Tundra / alpine ---------------------------------------------------------------------------------------------
  { id: 'dwarf_willow', name: 'Dwarf willow', kind: 'shrub', leafType: 'broadleaf', habit: 'deciduous', biomes: { tundra: 1, alpine: 0.7, boreal_forest: 0.1 }, heightM: [0.15, 0.5], spread: 2.5, trunkColour: '#6d5a45', leafColour: '#6f8f4a', autumnColour: '#c8a03a', maxSlope: 0.7 },
  { id: 'lichen_rock', name: 'Lichen-covered rock', kind: 'rock', leafType: 'none', habit: 'evergreen', biomes: { tundra: 1, alpine: 1, boreal_forest: 0.4 }, heightM: [0.3, 1.5], spread: 1.4, trunkColour: '#7d7f78', leafColour: '#a9b08a', maxSlope: 1 },
  { id: 'sedge_grass', name: 'Sedge', kind: 'grass', leafType: 'broadleaf', habit: 'deciduous', biomes: { tundra: 1, alpine: 0.8, wetland: 0.6, boreal_forest: 0.2 }, heightM: [0.2, 0.5], spread: 1.5, trunkColour: '#8fa05a', leafColour: '#8fa05a', autumnColour: '#b59a4a', maxSlope: 0.6, waterAffinity: 0.4 },
  { id: 'cushion_flower', name: 'Cushion plant (moss campion)', kind: 'flower', leafType: 'broadleaf', habit: 'evergreen', biomes: { tundra: 0.8, alpine: 1 }, heightM: [0.05, 0.15], spread: 3, trunkColour: '#5f7d46', leafColour: '#5f7d46', flowers: { colour: '#e58cb5', months: [6, 7, 8] }, maxSlope: 0.8 },
  { id: 'alpine_gentian', name: 'Alpine gentian', kind: 'flower', leafType: 'broadleaf', habit: 'deciduous', biomes: { alpine: 0.8, tundra: 0.2 }, heightM: [0.05, 0.2], spread: 1.5, trunkColour: '#4f6d3f', leafColour: '#4f6d3f', flowers: { colour: '#2f4fb0', months: [7, 8] }, elevationM: [800, 5000], maxSlope: 0.8 },
  { id: 'glacial_boulder', name: 'Glacial boulder', kind: 'rock', leafType: 'none', habit: 'evergreen', biomes: { alpine: 0.9, tundra: 0.6, ice_sheet: 0.5, boreal_forest: 0.2 }, heightM: [0.8, 3], spread: 1.3, trunkColour: '#8a8b86', leafColour: '#8a8b86', maxSlope: 1 },
  { id: 'ice_hummock', name: 'Ice hummock / sastrugi', kind: 'rock', leafType: 'none', habit: 'evergreen', biomes: { ice_sheet: 1 }, heightM: [0.4, 2], spread: 2.5, trunkColour: '#e6eef7', leafColour: '#e6eef7', maxSlope: 1 },
  // ---- Hot desert --------------------------------------------------------------------------------------------------
  { id: 'saguaro_cactus', name: 'Columnar cactus (saguaro-like)', kind: 'cactus', leafType: 'succulent', habit: 'evergreen', biomes: { hot_desert: 0.7 }, heightM: [3, 12], spread: 0.25, trunkColour: '#4f7a3f', leafColour: '#587f45', flowers: { colour: '#f2f0d8', months: [5, 6] }, fruit: { name: 'cactus fruit', colour: '#c23b4a', sizeM: 0.06, months: [6, 7] }, elevationM: [0, 1400], maxSlope: 0.6 },
  { id: 'agave', name: 'Agave', kind: 'cactus', leafType: 'succulent', habit: 'evergreen', biomes: { hot_desert: 1, cold_desert: 0.2, mediterranean: 0.15 }, heightM: [0.8, 2], spread: 1.2, trunkColour: '#7d9a7a', leafColour: '#7d9a7a', flowers: { colour: '#d9c96a', months: [6, 7, 8] }, maxSlope: 0.7 },
  { id: 'prickly_pear', name: 'Prickly pear', kind: 'cactus', leafType: 'succulent', habit: 'evergreen', biomes: { hot_desert: 0.6, cold_desert: 0.3, mediterranean: 0.1 }, heightM: [0.6, 2], spread: 1.1, trunkColour: '#6f9a5a', leafColour: '#6f9a5a', flowers: { colour: '#f2c33c', months: [5, 6] }, fruit: { name: 'prickly pear', colour: '#b02a5b', sizeM: 0.06, months: [8, 9, 10] }, maxSlope: 0.7 },
  { id: 'creosote_bush', name: 'Creosote bush', kind: 'shrub', leafType: 'broadleaf', habit: 'evergreen', biomes: { hot_desert: 1, cold_desert: 0.5 }, heightM: [1, 3], spread: 1.2, trunkColour: '#6b5b48', leafColour: '#6f7f3e', flowers: { colour: '#e2c94a', months: [3, 4, 5] }, maxSlope: 0.6 },
  { id: 'date_palm', name: 'Date palm (oasis)', kind: 'palm', leafType: 'palm', habit: 'evergreen', biomes: { hot_desert: 0.6, mediterranean: 0.1 }, heightM: [12, 22], spread: 0.5, trunkColour: '#8b7355', leafColour: '#4f7a3a', fruit: { name: 'date', colour: '#8a4b1f', sizeM: 0.04, months: [8, 9, 10] }, elevationM: [-50, 1200], maxSlope: 0.3, waterAffinity: 1 },
  { id: 'desert_bunchgrass', name: 'Desert bunchgrass', kind: 'grass', leafType: 'broadleaf', habit: 'evergreen', biomes: { hot_desert: 1, cold_desert: 0.8, steppe: 0.4 }, heightM: [0.3, 0.7], spread: 1.2, trunkColour: '#b8a862', leafColour: '#b8a862', maxSlope: 0.7 },
  { id: 'desert_marigold', name: 'Desert marigold', kind: 'flower', leafType: 'broadleaf', habit: 'deciduous', biomes: { hot_desert: 1 }, heightM: [0.2, 0.5], spread: 1.2, trunkColour: '#8fa06a', leafColour: '#8fa06a', flowers: { colour: '#f0c33a', months: [3, 4, 5] }, maxSlope: 0.6 },
  { id: 'sandstone_rock', name: 'Sandstone outcrop', kind: 'rock', leafType: 'none', habit: 'evergreen', biomes: { hot_desert: 1, cold_desert: 0.5, steppe: 0.3 }, heightM: [0.5, 3], spread: 1.6, trunkColour: '#c4915c', leafColour: '#c4915c', maxSlope: 1 },
  // ---- Cold desert / steppe ----------------------------------------------------------------------------------------
  { id: 'sagebrush', name: 'Sagebrush', kind: 'shrub', leafType: 'broadleaf', habit: 'evergreen', biomes: { cold_desert: 1, steppe: 0.7 }, heightM: [0.6, 2], spread: 1.2, trunkColour: '#6e6350', leafColour: '#8c9a7a', maxSlope: 0.7 },
  { id: 'saltbush', name: 'Saltbush', kind: 'shrub', leafType: 'broadleaf', habit: 'evergreen', biomes: { cold_desert: 1, hot_desert: 0.3, steppe: 0.3 }, heightM: [0.5, 1.5], spread: 1.3, trunkColour: '#7a7361', leafColour: '#9aa58b', maxSlope: 0.6 },
  { id: 'feather_grass', name: 'Feather grass', kind: 'grass', leafType: 'broadleaf', habit: 'deciduous', biomes: { steppe: 1, temperate_grassland: 0.5, cold_desert: 0.4 }, heightM: [0.4, 0.9], spread: 1.2, trunkColour: '#c2b56a', leafColour: '#c2b56a', autumnColour: '#cbb277', maxSlope: 0.7 },
  { id: 'wormwood', name: 'Wormwood', kind: 'shrub', leafType: 'broadleaf', habit: 'evergreen', biomes: { steppe: 1, cold_desert: 0.6 }, heightM: [0.4, 1.2], spread: 1.2, trunkColour: '#847a63', leafColour: '#9fa88a', flowers: { colour: '#d8d27a', months: [7, 8, 9] }, maxSlope: 0.7 },
  { id: 'juniper', name: 'Juniper', kind: 'tree', leafType: 'needle', habit: 'evergreen', biomes: { cold_desert: 0.5, steppe: 0.3, mediterranean: 0.3 }, heightM: [3, 10], spread: 0.7, trunkColour: '#6e5a48', leafColour: '#4f6f45', elevationM: [0, 3000], maxSlope: 0.8 },
  // ---- Savanna -----------------------------------------------------------------------------------------------------
  { id: 'acacia', name: 'Umbrella acacia', kind: 'tree', leafType: 'broadleaf', habit: 'seasonal-dry', biomes: { savanna: 1, tropical_seasonal_forest: 0.2, steppe: 0.1 }, heightM: [5, 15], spread: 1.4, trunkColour: '#5a4a38', leafColour: '#5f8a3a', flowers: { colour: '#f2e59a', months: [10, 11, 12] }, elevationM: [0, 2000], maxSlope: 0.5 },
  { id: 'baobab', name: 'Baobab', kind: 'tree', leafType: 'broadleaf', habit: 'seasonal-dry', biomes: { savanna: 0.3 }, heightM: [10, 25], spread: 0.9, trunkColour: '#9a8b78', leafColour: '#6d8f45', flowers: { colour: '#f4f0e0', months: [10, 11, 12] }, fruit: { name: 'baobab fruit', colour: '#a08c6a', sizeM: 0.15, months: [4, 5, 6] }, elevationM: [0, 1200], maxSlope: 0.4 },
  { id: 'marula', name: 'Marula', kind: 'tree', leafType: 'broadleaf', habit: 'seasonal-dry', biomes: { savanna: 0.4 }, heightM: [7, 15], spread: 1.1, trunkColour: '#7a6a58', leafColour: '#5b8a3f', fruit: { name: 'marula', colour: '#d8c24a', sizeM: 0.04, months: [8, 9] }, elevationM: [0, 1600], maxSlope: 0.5 },
  { id: 'elephant_grass', name: 'Elephant grass', kind: 'grass', leafType: 'broadleaf', habit: 'seasonal-dry', biomes: { savanna: 1, tropical_seasonal_forest: 0.6, wetland: 0.6 }, heightM: [1.5, 3.5], spread: 0.8, trunkColour: '#8ea649', leafColour: '#8ea649', autumnColour: '#c2b16a', maxSlope: 0.6 },
  { id: 'doum_palm', name: 'Doum palm', kind: 'palm', leafType: 'palm', habit: 'evergreen', biomes: { savanna: 0.5, hot_desert: 0.1 }, heightM: [8, 15], spread: 0.6, trunkColour: '#8a7a62', leafColour: '#5f8a45', fruit: { name: 'doum nut', colour: '#b8702c', sizeM: 0.06, months: [1, 2, 3] }, elevationM: [0, 1400], maxSlope: 0.3, waterAffinity: 0.7 },
  { id: 'termite_mound', name: 'Termite mound', kind: 'rock', leafType: 'none', habit: 'evergreen', biomes: { savanna: 0.8, tropical_seasonal_forest: 0.2 }, heightM: [1, 3], spread: 0.8, trunkColour: '#a67c52', leafColour: '#a67c52', maxSlope: 0.4 },
  { id: 'lantana_shrub', name: 'Flowering scrub (lantana-like)', kind: 'shrub', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_seasonal_forest: 0.8, savanna: 0.5 }, heightM: [0.8, 2], spread: 1.3, trunkColour: '#6e5e4a', leafColour: '#5c8f3a', flowers: { colour: '#f28c3a', months: [4, 5, 6, 7, 8, 9, 10] }, maxSlope: 0.7 },
  // ---- Tropical rainforest -----------------------------------------------------------------------------------------
  { id: 'kapok', name: 'Kapok (emergent)', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_rainforest: 0.5, tropical_seasonal_forest: 0.2 }, heightM: [30, 60], spread: 0.6, trunkColour: '#8a8478', leafColour: '#3e7a35', elevationM: [0, 1200], maxSlope: 0.6 },
  { id: 'mahogany', name: 'Mahogany-like canopy tree', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_rainforest: 1, tropical_seasonal_forest: 0.4 }, heightM: [20, 40], spread: 0.7, trunkColour: '#6b4f3a', leafColour: '#2f6e30', elevationM: [0, 1500], maxSlope: 0.7 },
  { id: 'rubber_tree', name: 'Rubber tree', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_rainforest: 0.6, tropical_seasonal_forest: 0.3 }, heightM: [15, 30], spread: 0.6, trunkColour: '#9a8f80', leafColour: '#4a8a3c', elevationM: [0, 800], maxSlope: 0.6 },
  { id: 'banana', name: 'Banana', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_rainforest: 0.6, tropical_seasonal_forest: 0.5, wetland: 0.15 }, heightM: [3, 6], spread: 0.9, trunkColour: '#7f9a4a', leafColour: '#4f9a3a', fruit: { name: 'banana', colour: '#e0d24a', sizeM: 0.15, months: ALL_MONTHS }, elevationM: [0, 1800], maxSlope: 0.5, waterAffinity: 0.3 },
  { id: 'rainforest_palm', name: 'Rainforest palm', kind: 'palm', leafType: 'palm', habit: 'evergreen', biomes: { tropical_rainforest: 0.8, tropical_seasonal_forest: 0.3, mangrove: 0.1, wetland: 0.4 }, heightM: [8, 20], spread: 0.5, trunkColour: '#8a7f6a', leafColour: '#3f8a3a', elevationM: [0, 1200], maxSlope: 0.7 },
  { id: 'tree_fern', name: 'Tree fern', kind: 'shrub', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_rainforest: 1, temperate_rainforest: 0.6, tropical_seasonal_forest: 0.4 }, heightM: [1.5, 5], spread: 1.2, trunkColour: '#5a4a3a', leafColour: '#3f8a3a', maxSlope: 0.8 },
  { id: 'fern_understory', name: 'Fern understory', kind: 'grass', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_rainforest: 1, temperate_rainforest: 1, tropical_seasonal_forest: 0.5, wetland: 0.2 }, heightM: [0.4, 1.2], spread: 1.5, trunkColour: '#3f7f3a', leafColour: '#3f7f3a', maxSlope: 0.8 },
  { id: 'heliconia', name: 'Heliconia', kind: 'flower', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_rainforest: 0.6, tropical_seasonal_forest: 0.4, wetland: 0.2 }, heightM: [1, 2.5], spread: 0.8, trunkColour: '#3f8a3a', leafColour: '#3f8a3a', flowers: { colour: '#e0402a', months: ALL_MONTHS }, elevationM: [0, 1500], maxSlope: 0.6 },
  // ---- Tropical seasonal (monsoon) forest --------------------------------------------------------------------------
  { id: 'teak', name: 'Teak', kind: 'tree', leafType: 'broadleaf', habit: 'seasonal-dry', biomes: { tropical_seasonal_forest: 1, savanna: 0.1 }, heightM: [20, 40], spread: 0.5, trunkColour: '#8f7f6a', leafColour: '#5e8f3c', flowers: { colour: '#f0ecd8', months: [6, 7, 8] }, elevationM: [0, 1200], maxSlope: 0.6 },
  { id: 'sal', name: 'Sal', kind: 'tree', leafType: 'broadleaf', habit: 'seasonal-dry', biomes: { tropical_seasonal_forest: 1 }, heightM: [20, 35], spread: 0.5, trunkColour: '#6e5a48', leafColour: '#4f8a3a', elevationM: [0, 1500], maxSlope: 0.6 },
  { id: 'mango', name: 'Mango', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_seasonal_forest: 0.5, tropical_rainforest: 0.2, savanna: 0.1 }, heightM: [10, 25], spread: 1, trunkColour: '#6b5a48', leafColour: '#2f6b2e', flowers: { colour: '#e8dfa8', months: [1, 2, 3] }, fruit: { name: 'mango', colour: '#e0a13a', sizeM: 0.1, months: [4, 5, 6] }, elevationM: [0, 1200], maxSlope: 0.5 },
  { id: 'bamboo', name: 'Clumping bamboo', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_seasonal_forest: 0.7, tropical_rainforest: 0.4, temperate_deciduous_forest: 0.05 }, heightM: [6, 18], spread: 0.35, trunkColour: '#9fb04a', leafColour: '#7fb04a', elevationM: [0, 2500], maxSlope: 0.7, waterAffinity: 0.4 },
  { id: 'coconut_palm', name: 'Coconut palm', kind: 'palm', leafType: 'palm', habit: 'evergreen', biomes: { tropical_seasonal_forest: 0.6, tropical_rainforest: 0.4, mangrove: 0.3, savanna: 0.1 }, heightM: [15, 28], spread: 0.5, trunkColour: '#9a8a70', leafColour: '#4f8a3a', fruit: { name: 'coconut', colour: '#7a9a3a', sizeM: 0.25, months: ALL_MONTHS }, elevationM: [-5, 300], maxSlope: 0.4, waterAffinity: 0.9 },
  { id: 'papaya', name: 'Papaya', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_seasonal_forest: 0.4, tropical_rainforest: 0.4 }, heightM: [3, 7], spread: 0.7, trunkColour: '#8f8a70', leafColour: '#4f9a3f', fruit: { name: 'papaya', colour: '#e4a43a', sizeM: 0.2, months: ALL_MONTHS }, elevationM: [0, 1500], maxSlope: 0.5 },
  // ---- Mangrove ----------------------------------------------------------------------------------------------------
  { id: 'red_mangrove', name: 'Red mangrove', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { mangrove: 1 }, heightM: [5, 15], spread: 0.9, trunkColour: '#6b4f3a', leafColour: '#3e7a3a', elevationM: [-5, 40], maxSlope: 0.2, waterAffinity: 1 },
  { id: 'black_mangrove', name: 'Black mangrove', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { mangrove: 0.7 }, heightM: [4, 12], spread: 0.9, trunkColour: '#4f4034', leafColour: '#4d7d45', elevationM: [-5, 40], maxSlope: 0.2, waterAffinity: 1 },
  { id: 'nipa_palm', name: 'Nipa palm', kind: 'palm', leafType: 'palm', habit: 'evergreen', biomes: { mangrove: 0.6, wetland: 0.3 }, heightM: [4, 9], spread: 1.1, trunkColour: '#6f6a50', leafColour: '#4f8a3a', elevationM: [-5, 40], maxSlope: 0.2, waterAffinity: 1 },
  { id: 'mangrove_fern', name: 'Mangrove fern', kind: 'grass', leafType: 'broadleaf', habit: 'evergreen', biomes: { mangrove: 0.5, wetland: 0.4 }, heightM: [0.5, 1.5], spread: 1.3, trunkColour: '#5a8a4a', leafColour: '#5a8a4a', elevationM: [-5, 40], maxSlope: 0.3, waterAffinity: 0.8 },
  // ---- Mediterranean -----------------------------------------------------------------------------------------------
  { id: 'olive', name: 'Olive', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { mediterranean: 1 }, heightM: [5, 12], spread: 1.1, trunkColour: '#7a6b57', leafColour: '#7f9a6a', flowers: { colour: '#eee9c8', months: [5] }, fruit: { name: 'olive', colour: '#3c3f2e', sizeM: 0.02, months: [10, 11, 12] }, elevationM: [0, 900], maxSlope: 0.6 },
  { id: 'cork_oak', name: 'Cork oak', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { mediterranean: 0.8 }, heightM: [10, 18], spread: 1, trunkColour: '#7c6650', leafColour: '#4f7a45', elevationM: [0, 1000], maxSlope: 0.6 },
  { id: 'holm_oak', name: 'Holm oak', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { mediterranean: 0.8 }, heightM: [10, 20], spread: 0.9, trunkColour: '#5f5044', leafColour: '#3f6a3a', elevationM: [0, 1400], maxSlope: 0.7 },
  { id: 'cypress', name: 'Italian cypress', kind: 'tree', leafType: 'needle', habit: 'evergreen', biomes: { mediterranean: 0.5 }, heightM: [12, 25], spread: 0.15, trunkColour: '#6a5a48', leafColour: '#2f5a30', elevationM: [0, 1200], maxSlope: 0.6 },
  { id: 'stone_pine', name: 'Stone pine', kind: 'tree', leafType: 'needle', habit: 'evergreen', biomes: { mediterranean: 0.7 }, heightM: [12, 25], spread: 0.9, trunkColour: '#7f6a52', leafColour: '#3f6f3a', elevationM: [0, 1000], maxSlope: 0.6 },
  { id: 'citrus', name: 'Orange / lemon', kind: 'tree', leafType: 'broadleaf', habit: 'evergreen', biomes: { mediterranean: 0.4 }, heightM: [3, 7], spread: 1, trunkColour: '#6b5744', leafColour: '#2e6b2f', flowers: { colour: '#ffffff', months: [3, 4] }, fruit: { name: 'orange', colour: '#f28c1e', sizeM: 0.08, months: [12, 1, 2, 3] }, elevationM: [0, 600], maxSlope: 0.4 },
  { id: 'fig', name: 'Fig', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { mediterranean: 0.4 }, heightM: [4, 9], spread: 1.2, trunkColour: '#8a8074', leafColour: '#4e8a3c', autumnColour: '#b9a244', fruit: { name: 'fig', colour: '#6a3d6b', sizeM: 0.05, months: [8, 9] }, elevationM: [0, 800], maxSlope: 0.5 },
  { id: 'lavender', name: 'Lavender', kind: 'flower', leafType: 'broadleaf', habit: 'evergreen', biomes: { mediterranean: 1 }, heightM: [0.4, 0.8], spread: 1.2, trunkColour: '#8a9a7a', leafColour: '#8a9a7a', flowers: { colour: '#8a6fc8', months: [6, 7, 8] }, maxSlope: 0.7 },
  { id: 'maquis_shrub', name: 'Maquis shrub (rockrose / lentisk)', kind: 'shrub', leafType: 'broadleaf', habit: 'evergreen', biomes: { mediterranean: 1 }, heightM: [1, 3], spread: 1.2, trunkColour: '#6a5a48', leafColour: '#5d7d45', flowers: { colour: '#e9a4c8', months: [4, 5, 6] }, maxSlope: 0.8 },
  { id: 'mediterranean_grass', name: 'Dry meadow grass', kind: 'grass', leafType: 'broadleaf', habit: 'deciduous', biomes: { mediterranean: 1 }, heightM: [0.3, 0.7], spread: 1.3, trunkColour: '#b7ad62', leafColour: '#b7ad62', autumnColour: '#c9b66e', maxSlope: 0.7 },
  { id: 'limestone_rock', name: 'Limestone outcrop', kind: 'rock', leafType: 'none', habit: 'evergreen', biomes: { mediterranean: 0.8, alpine: 0.3 }, heightM: [0.5, 2.5], spread: 1.5, trunkColour: '#c9c2ad', leafColour: '#c9c2ad', maxSlope: 1 },
  // ---- Temperate deciduous forest ----------------------------------------------------------------------------------
  { id: 'oak', name: 'Oak', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 1, temperate_grassland: 0.4, mediterranean: 0.2, temperate_rainforest: 0.2 }, heightM: [15, 30], spread: 0.9, trunkColour: '#5e4d3c', leafColour: '#4a7c34', autumnColour: '#b5772d', elevationM: [0, 1500], maxSlope: 0.7 },
  { id: 'beech', name: 'Beech', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.9, temperate_rainforest: 0.2 }, heightM: [20, 35], spread: 0.7, trunkColour: '#8a8478', leafColour: '#4f8a36', autumnColour: '#c88a3a', elevationM: [0, 1600], maxSlope: 0.7 },
  { id: 'maple', name: 'Maple', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.8, boreal_forest: 0.1 }, heightM: [15, 30], spread: 0.8, trunkColour: '#6b5a4a', leafColour: '#5a9a3c', autumnColour: '#d9442a', elevationM: [0, 1500], maxSlope: 0.7 },
  { id: 'birch', name: 'Birch', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.5, boreal_forest: 0.9, wetland: 0.2 }, heightM: [12, 25], spread: 0.5, trunkColour: '#e8e4dc', leafColour: '#6fa64a', autumnColour: '#e2b52f', elevationM: [0, 2000], maxSlope: 0.8 },
  { id: 'apple', name: 'Apple', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.25, temperate_grassland: 0.1 }, heightM: [4, 9], spread: 1.1, trunkColour: '#6b5744', leafColour: '#4e8a3c', autumnColour: '#b99a3a', flowers: { colour: '#f7dbe4', months: [4, 5] }, fruit: { name: 'apple', colour: '#c9333a', sizeM: 0.08, months: [8, 9, 10] }, elevationM: [0, 1200], maxSlope: 0.5 },
  { id: 'cherry', name: 'Cherry', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.25 }, heightM: [6, 12], spread: 0.9, trunkColour: '#5f4a40', leafColour: '#4f8a3a', autumnColour: '#d67a2a', flowers: { colour: '#f9e4ec', months: [4] }, fruit: { name: 'cherry', colour: '#8c1d2c', sizeM: 0.02, months: [6, 7] }, elevationM: [0, 1200], maxSlope: 0.6 },
  { id: 'plum', name: 'Plum', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.2, mediterranean: 0.1 }, heightM: [4, 8], spread: 1, trunkColour: '#5a4a42', leafColour: '#4a8038', autumnColour: '#c99a3a', flowers: { colour: '#ffffff', months: [3, 4] }, fruit: { name: 'plum', colour: '#5a2d6b', sizeM: 0.05, months: [8, 9] }, elevationM: [0, 1000], maxSlope: 0.5 },
  { id: 'hazel', name: 'Hazel', kind: 'shrub', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 1, temperate_rainforest: 0.3 }, heightM: [3, 6], spread: 1.2, trunkColour: '#6e5e4e', leafColour: '#5c9040', autumnColour: '#c9a23a', fruit: { name: 'hazelnut', colour: '#8b5a2b', sizeM: 0.02, months: [9, 10] }, elevationM: [0, 1500], maxSlope: 0.7 },
  { id: 'bramble', name: 'Bramble (blackberry)', kind: 'shrub', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.7, temperate_rainforest: 0.5 }, heightM: [0.8, 2], spread: 1.6, trunkColour: '#5a4a3f', leafColour: '#4f8a3a', autumnColour: '#9a5a30', flowers: { colour: '#f8f0f2', months: [6, 7] }, fruit: { name: 'blackberry', colour: '#2a1a2e', sizeM: 0.015, months: [8, 9] }, maxSlope: 0.7 },
  { id: 'poppy', name: 'Poppy', kind: 'flower', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.6, temperate_grassland: 0.8, mediterranean: 0.5, steppe: 0.3 }, heightM: [0.3, 0.7], spread: 1, trunkColour: '#6f9a45', leafColour: '#6f9a45', flowers: { colour: '#d8261f', months: [5, 6, 7] }, maxSlope: 0.6 },
  { id: 'daisy', name: 'Ox-eye daisy', kind: 'flower', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 1, temperate_grassland: 1, temperate_rainforest: 0.4, boreal_forest: 0.2 }, heightM: [0.1, 0.4], spread: 1.5, trunkColour: '#6f9a45', leafColour: '#6f9a45', flowers: { colour: '#f7f7f0', months: [5, 6, 7, 8, 9] }, maxSlope: 0.6 },
  { id: 'meadow_grass', name: 'Meadow grass', kind: 'grass', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 1, temperate_rainforest: 0.6, boreal_forest: 0.6, mediterranean: 0.3, wetland: 0.5, temperate_grassland: 0.5 }, heightM: [0.2, 0.6], spread: 1.5, trunkColour: '#6f9a45', leafColour: '#6f9a45', autumnColour: '#a89a52', maxSlope: 0.7 },
  { id: 'granite_boulder', name: 'Granite boulder', kind: 'rock', leafType: 'none', habit: 'evergreen', biomes: { temperate_deciduous_forest: 0.5, temperate_grassland: 0.3, boreal_forest: 0.7, steppe: 0.5, savanna: 0.4, cold_desert: 0.5, alpine: 0.6, tundra: 0.5, tropical_seasonal_forest: 0.3, tropical_rainforest: 0.2, mediterranean: 0.3 }, heightM: [0.5, 2.5], spread: 1.4, trunkColour: '#8d8b84', leafColour: '#8d8b84', maxSlope: 1 },
  // ---- Temperate rainforest ----------------------------------------------------------------------------------------
  { id: 'redwood', name: 'Giant conifer (redwood-like)', kind: 'tree', leafType: 'needle', habit: 'evergreen', biomes: { temperate_rainforest: 1 }, heightM: [40, 90], spread: 0.25, trunkColour: '#7a3f2f', leafColour: '#2f5f33', elevationM: [0, 900], maxSlope: 0.7 },
  { id: 'western_hemlock', name: 'Western hemlock', kind: 'tree', leafType: 'needle', habit: 'evergreen', biomes: { temperate_rainforest: 0.8, boreal_forest: 0.1 }, heightM: [30, 55], spread: 0.35, trunkColour: '#5f4a3f', leafColour: '#355f38', elevationM: [0, 1500], maxSlope: 0.8 },
  { id: 'sword_fern', name: 'Sword fern', kind: 'shrub', leafType: 'broadleaf', habit: 'evergreen', biomes: { temperate_rainforest: 1, temperate_deciduous_forest: 0.2 }, heightM: [0.6, 1.5], spread: 1.5, trunkColour: '#3f7f3a', leafColour: '#3f7f3a', maxSlope: 0.8 },
  { id: 'moss_rock', name: 'Moss-covered rock', kind: 'rock', leafType: 'none', habit: 'evergreen', biomes: { temperate_rainforest: 1, tropical_rainforest: 0.6, wetland: 0.3 }, heightM: [0.4, 2], spread: 1.5, trunkColour: '#6f8a5a', leafColour: '#6f8a5a', maxSlope: 1 },
  // ---- Temperate grassland -----------------------------------------------------------------------------------------
  { id: 'prairie_grass', name: 'Prairie grass', kind: 'grass', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_grassland: 1, steppe: 0.4 }, heightM: [0.5, 1.5], spread: 1, trunkColour: '#a3a852', leafColour: '#a3a852', autumnColour: '#c2a45a', maxSlope: 0.6 },
  { id: 'wild_sunflower', name: 'Wild sunflower', kind: 'flower', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_grassland: 0.6, steppe: 0.2 }, heightM: [1, 2.5], spread: 0.5, trunkColour: '#6f9a45', leafColour: '#6f9a45', flowers: { colour: '#f2c025', months: [7, 8, 9] }, maxSlope: 0.5 },
  { id: 'prairie_wildflower', name: 'Prairie coneflower', kind: 'flower', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_grassland: 1 }, heightM: [0.3, 0.9], spread: 1, trunkColour: '#6f9a45', leafColour: '#6f9a45', flowers: { colour: '#c85a9a', months: [6, 7, 8] }, maxSlope: 0.6 },
  { id: 'cottonwood', name: 'Cottonwood (riparian)', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_grassland: 0.6, steppe: 0.3, cold_desert: 0.2 }, heightM: [15, 30], spread: 0.8, trunkColour: '#8a8072', leafColour: '#5f9a3c', autumnColour: '#e6c33a', elevationM: [0, 2200], maxSlope: 0.4, waterAffinity: 0.85 },
  { id: 'wild_rose', name: 'Wild rose', kind: 'shrub', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_grassland: 0.5, temperate_deciduous_forest: 0.3, steppe: 0.3 }, heightM: [0.8, 2], spread: 1.3, trunkColour: '#6b5a4a', leafColour: '#5a8a3c', autumnColour: '#b9843a', flowers: { colour: '#f0a8c0', months: [6] }, fruit: { name: 'rosehip', colour: '#c8322a', sizeM: 0.015, months: [9, 10] }, maxSlope: 0.7 },
  // ---- Boreal forest -----------------------------------------------------------------------------------------------
  { id: 'spruce', name: 'Spruce', kind: 'tree', leafType: 'needle', habit: 'evergreen', biomes: { boreal_forest: 1, temperate_rainforest: 0.5, temperate_deciduous_forest: 0.15 }, heightM: [15, 35], spread: 0.3, trunkColour: '#5a4a3c', leafColour: '#2f5a35', elevationM: [0, 2200], maxSlope: 0.75 },
  { id: 'pine', name: 'Pine', kind: 'tree', leafType: 'needle', habit: 'evergreen', biomes: { boreal_forest: 0.8, temperate_deciduous_forest: 0.2, mediterranean: 0.2, steppe: 0.05 }, heightM: [15, 30], spread: 0.45, trunkColour: '#a06a48', leafColour: '#3f6a3a', elevationM: [0, 2400], maxSlope: 0.8 },
  { id: 'fir', name: 'Fir', kind: 'tree', leafType: 'needle', habit: 'evergreen', biomes: { boreal_forest: 0.6, temperate_rainforest: 0.4, temperate_deciduous_forest: 0.1 }, heightM: [20, 40], spread: 0.3, trunkColour: '#6a5a4c', leafColour: '#2e5c34', elevationM: [0, 2300], maxSlope: 0.75 },
  { id: 'larch', name: 'Larch (deciduous conifer)', kind: 'tree', leafType: 'needle', habit: 'deciduous', biomes: { boreal_forest: 0.7 }, heightM: [15, 35], spread: 0.35, trunkColour: '#7a5f4a', leafColour: '#6fa04a', autumnColour: '#d9a02f', elevationM: [0, 2400], maxSlope: 0.8 },
  { id: 'lingonberry', name: 'Lingonberry', kind: 'shrub', leafType: 'broadleaf', habit: 'evergreen', biomes: { boreal_forest: 1 }, heightM: [0.1, 0.3], spread: 2, trunkColour: '#4f5a3a', leafColour: '#3f6a3a', flowers: { colour: '#f4d6dc', months: [6] }, fruit: { name: 'lingonberry', colour: '#b5202c', sizeM: 0.008, months: [8, 9] }, maxSlope: 0.7 },
  { id: 'boreal_moss', name: 'Feather moss carpet', kind: 'grass', leafType: 'broadleaf', habit: 'evergreen', biomes: { boreal_forest: 1 }, heightM: [0.05, 0.15], spread: 4, trunkColour: '#5f8a4a', leafColour: '#5f8a4a', maxSlope: 0.8 },
  { id: 'fireweed', name: 'Fireweed', kind: 'flower', leafType: 'broadleaf', habit: 'deciduous', biomes: { boreal_forest: 0.8 }, heightM: [0.6, 1.5], spread: 0.6, trunkColour: '#5f8a4a', leafColour: '#5f8a4a', flowers: { colour: '#d05aa8', months: [7, 8] }, maxSlope: 0.7 },
  // ---- Wetland -----------------------------------------------------------------------------------------------------
  { id: 'reed', name: 'Common reed', kind: 'reed', leafType: 'broadleaf', habit: 'deciduous', biomes: { wetland: 1, mangrove: 0.1, temperate_grassland: 0.05 }, heightM: [1.5, 3.5], spread: 0.6, trunkColour: '#8fa05a', leafColour: '#8fa05a', autumnColour: '#c2b070', maxSlope: 0.2, waterAffinity: 1 },
  { id: 'cattail', name: 'Cattail', kind: 'reed', leafType: 'broadleaf', habit: 'deciduous', biomes: { wetland: 1 }, heightM: [1.2, 2.5], spread: 0.5, trunkColour: '#7f9a4a', leafColour: '#7f9a4a', autumnColour: '#b5a060', fruit: { name: 'seed head', colour: '#6b4a2a', sizeM: 0.03, months: [8, 9, 10] }, maxSlope: 0.2, waterAffinity: 1 },
  { id: 'willow', name: 'Willow', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { wetland: 1, temperate_deciduous_forest: 0.15, temperate_grassland: 0.2, boreal_forest: 0.2 }, heightM: [8, 20], spread: 1, trunkColour: '#6e5e4e', leafColour: '#7fa84a', autumnColour: '#c9b23a', elevationM: [0, 1800], maxSlope: 0.3, waterAffinity: 0.9 },
  { id: 'alder', name: 'Alder', kind: 'tree', leafType: 'broadleaf', habit: 'deciduous', biomes: { wetland: 0.7, temperate_deciduous_forest: 0.2, boreal_forest: 0.3 }, heightM: [10, 20], spread: 0.6, trunkColour: '#5a4f45', leafColour: '#4f8a3a', autumnColour: '#8f8a3a', elevationM: [0, 1800], maxSlope: 0.4, waterAffinity: 0.8 },
  { id: 'marsh_marigold', name: 'Marsh marigold', kind: 'flower', leafType: 'broadleaf', habit: 'deciduous', biomes: { wetland: 0.8 }, heightM: [0.2, 0.5], spread: 1.2, trunkColour: '#4f8a3a', leafColour: '#4f8a3a', flowers: { colour: '#f2c31e', months: [4, 5] }, maxSlope: 0.3, waterAffinity: 0.9 },
  // ---- Crops (cultivated; planted in rows on farmland) -------------------------------------------------------------
  { id: 'crop_wheat', name: 'Wheat', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 1, temperate_grassland: 1, mediterranean: 0.8, steppe: 0.7, boreal_forest: 0.2, tropical_seasonal_forest: 0.2, hot_desert: 0.3, cold_desert: 0.2 }, heightM: [0.6, 1], spread: 1, trunkColour: '#7fa040', leafColour: '#7fa040', fruit: { name: 'ripe ears', colour: '#d9b85a', sizeM: 0.05, months: [7, 8] }, maxSlope: 0.3, cultivated: true },
  { id: 'crop_barley', name: 'Barley', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.6, boreal_forest: 0.7, temperate_grassland: 0.5, steppe: 0.5, mediterranean: 0.4 }, heightM: [0.6, 1], spread: 1, trunkColour: '#86a548', leafColour: '#86a548', fruit: { name: 'ripe ears', colour: '#d6b467', sizeM: 0.05, months: [7, 8] }, maxSlope: 0.35, cultivated: true },
  { id: 'crop_maize', name: 'Maize', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.8, temperate_grassland: 0.9, savanna: 0.7, tropical_seasonal_forest: 0.6, mediterranean: 0.3, steppe: 0.2 }, heightM: [1.8, 2.8], spread: 0.4, trunkColour: '#6f9a3a', leafColour: '#6f9a3a', fruit: { name: 'cob', colour: '#e6c847', sizeM: 0.2, months: [8, 9] }, maxSlope: 0.3, cultivated: true },
  { id: 'crop_rice', name: 'Paddy rice', kind: 'crop', leafType: 'broadleaf', habit: 'seasonal-dry', biomes: { tropical_seasonal_forest: 1, tropical_rainforest: 0.7, wetland: 0.8 }, heightM: [0.6, 1.1], spread: 1, trunkColour: '#6fa83a', leafColour: '#6fa83a', fruit: { name: 'ripe panicles', colour: '#d6b86a', sizeM: 0.05, months: [9, 10, 11] }, elevationM: [-5, 2000], maxSlope: 0.15, waterAffinity: 1, cultivated: true },
  { id: 'crop_sugarcane', name: 'Sugarcane', kind: 'crop', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_seasonal_forest: 0.7, tropical_rainforest: 0.5, savanna: 0.5, hot_desert: 0.2 }, heightM: [2.5, 4], spread: 0.3, trunkColour: '#9aa54a', leafColour: '#7fa83a', elevationM: [0, 1200], maxSlope: 0.3, cultivated: true },
  { id: 'crop_cotton', name: 'Cotton', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { savanna: 0.5, tropical_seasonal_forest: 0.5, steppe: 0.3, mediterranean: 0.2, temperate_grassland: 0.2, hot_desert: 0.2 }, heightM: [0.8, 1.4], spread: 0.9, trunkColour: '#5f8a3a', leafColour: '#5f8a3a', flowers: { colour: '#f4eec8', months: [7, 8] }, fruit: { name: 'cotton boll', colour: '#f4f2ea', sizeM: 0.04, months: [9, 10] }, maxSlope: 0.3, cultivated: true },
  { id: 'crop_mustard', name: 'Mustard / rapeseed', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { tropical_seasonal_forest: 0.4, temperate_grassland: 0.4, steppe: 0.3, temperate_deciduous_forest: 0.3 }, heightM: [0.8, 1.5], spread: 0.8, trunkColour: '#6f9a3a', leafColour: '#6f9a3a', flowers: { colour: '#f2d21e', months: [4, 5] }, maxSlope: 0.35, cultivated: true },
  { id: 'crop_sunflower', name: 'Sunflower', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_grassland: 0.6, steppe: 0.6, temperate_deciduous_forest: 0.4, mediterranean: 0.3 }, heightM: [1.5, 2.5], spread: 0.4, trunkColour: '#5f8a3a', leafColour: '#5f8a3a', flowers: { colour: '#f2b91e', months: [7, 8] }, maxSlope: 0.3, cultivated: true },
  { id: 'crop_soybean', name: 'Soybean', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.5, temperate_grassland: 0.6, savanna: 0.6, tropical_seasonal_forest: 0.3 }, heightM: [0.5, 1], spread: 1, trunkColour: '#5a9a3a', leafColour: '#5a9a3a', maxSlope: 0.3, cultivated: true },
  { id: 'crop_potato', name: 'Potato', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.5, boreal_forest: 0.6, temperate_grassland: 0.4 }, heightM: [0.4, 0.8], spread: 1.2, trunkColour: '#4f8a3a', leafColour: '#4f8a3a', flowers: { colour: '#e6e0f0', months: [6, 7] }, maxSlope: 0.35, cultivated: true },
  { id: 'crop_tea', name: 'Tea (highland)', kind: 'crop', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_seasonal_forest: 0.5, tropical_rainforest: 0.4 }, heightM: [0.8, 1.3], spread: 1.2, trunkColour: '#3f6a3a', leafColour: '#3f7a3a', elevationM: [300, 2500], maxSlope: 0.6, cultivated: true },
  { id: 'crop_coffee', name: 'Coffee (highland)', kind: 'crop', leafType: 'broadleaf', habit: 'evergreen', biomes: { tropical_rainforest: 0.3, tropical_seasonal_forest: 0.3, savanna: 0.1 }, heightM: [1.5, 3], spread: 0.8, trunkColour: '#5a4a3a', leafColour: '#2f6a2f', flowers: { colour: '#ffffff', months: [3, 4] }, fruit: { name: 'coffee cherry', colour: '#b8202a', sizeM: 0.012, months: [10, 11, 12, 1] }, elevationM: [600, 2200], maxSlope: 0.6, cultivated: true },
  { id: 'crop_vineyard', name: 'Grapevine', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { mediterranean: 1, temperate_deciduous_forest: 0.4, steppe: 0.1, temperate_grassland: 0.1 }, heightM: [1.5, 2], spread: 0.7, trunkColour: '#6b5a4a', leafColour: '#5f9a3c', autumnColour: '#c98a3a', fruit: { name: 'grape', colour: '#4a2a5a', sizeM: 0.03, months: [8, 9, 10] }, elevationM: [0, 1000], maxSlope: 0.5, cultivated: true },
  { id: 'crop_orchard_apple', name: 'Apple orchard', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { temperate_deciduous_forest: 0.7, temperate_grassland: 0.3, boreal_forest: 0.1 }, heightM: [3, 5], spread: 1.1, trunkColour: '#6b5744', leafColour: '#4e8a3c', autumnColour: '#b99a3a', flowers: { colour: '#f7dbe4', months: [4, 5] }, fruit: { name: 'apple', colour: '#c9333a', sizeM: 0.08, months: [8, 9, 10] }, elevationM: [0, 1200], maxSlope: 0.4, cultivated: true },
  { id: 'crop_orchard_citrus', name: 'Citrus orchard', kind: 'crop', leafType: 'broadleaf', habit: 'evergreen', biomes: { mediterranean: 0.7, tropical_seasonal_forest: 0.4, savanna: 0.2, hot_desert: 0.1 }, heightM: [3, 5], spread: 1, trunkColour: '#6b5744', leafColour: '#2e6b2f', flowers: { colour: '#ffffff', months: [3, 4] }, fruit: { name: 'orange', colour: '#f28c1e', sizeM: 0.08, months: [12, 1, 2, 3] }, elevationM: [0, 600], maxSlope: 0.4, cultivated: true },
  { id: 'crop_date_palm', name: 'Date palm grove', kind: 'crop', leafType: 'palm', habit: 'evergreen', biomes: { hot_desert: 0.6 }, heightM: [10, 20], spread: 0.5, trunkColour: '#8b7355', leafColour: '#4f7a3a', fruit: { name: 'date', colour: '#8a4b1f', sizeM: 0.04, months: [8, 9, 10] }, elevationM: [-50, 1200], maxSlope: 0.3, waterAffinity: 1, cultivated: true },
  { id: 'crop_oil_palm', name: 'Oil palm', kind: 'crop', leafType: 'palm', habit: 'evergreen', biomes: { tropical_rainforest: 1, tropical_seasonal_forest: 0.6 }, heightM: [8, 18], spread: 0.6, trunkColour: '#7f7060', leafColour: '#3f7a35', fruit: { name: 'oil palm fruit', colour: '#c8461e', sizeM: 0.04, months: ALL_MONTHS }, elevationM: [0, 800], maxSlope: 0.4, cultivated: true },
  { id: 'crop_millet', name: 'Millet / sorghum', kind: 'crop', leafType: 'broadleaf', habit: 'deciduous', biomes: { savanna: 1, steppe: 0.7, tropical_seasonal_forest: 0.3, hot_desert: 0.2 }, heightM: [1.5, 3], spread: 0.4, trunkColour: '#8fa048', leafColour: '#8fa048', fruit: { name: 'ripe heads', colour: '#c9a25a', sizeM: 0.08, months: [9, 10] }, maxSlope: 0.3, cultivated: true },
];

const BY_ID: ReadonlyMap<string, Species> = new Map(SPECIES.map((s) => [s.id, s]));

/** Look up a species by id (undefined when unknown). */
export function speciesById(id: string): Species | undefined {
  return BY_ID.get(id);
}

/** Wild (non-cultivated) species occurring in a biome, sorted by descending biome weight. */
export function speciesForBiome(biome: Biome): Species[] {
  return SPECIES.filter((s) => !s.cultivated && (s.biomes[biome] ?? 0) > 0).sort((a, b) => (b.biomes[biome] ?? 0) - (a.biomes[biome] ?? 0));
}

/** Cultivated crops plausible for a biome (irrigated crops included for deserts with mapped farmland), sorted by weight. */
export function cropsForBiome(biome: Biome): Species[] {
  return SPECIES.filter((s) => !!s.cultivated && (s.biomes[biome] ?? 0) > 0).sort((a, b) => (b.biomes[biome] ?? 0) - (a.biomes[biome] ?? 0));
}

export interface WeightedSpecies { species: Species; weight: number }

/** Wild species of the given kinds in a biome, paired with their relative weight (for seeded weighted picks). */
export function weightedSpeciesForBiome(biome: Biome, kinds?: readonly SpeciesKind[]): WeightedSpecies[] {
  return speciesForBiome(biome).filter((s) => !kinds || kinds.includes(s.kind)).map((s) => ({ species: s, weight: s.biomes[biome] ?? 0 }));
}

/** Weighted random pick using a seeded RNG; null when the list is empty or all weights are zero. */
export function pickWeighted(rng: Rng, entries: readonly WeightedSpecies[]): Species | null {
  let total = 0;
  for (const e of entries) total += e.weight;
  if (total <= 0) return null;
  let r = rng.next() * total;
  for (const e of entries) {
    r -= e.weight;
    if (r < 0) return e.species;
  }
  return entries[entries.length - 1].species;
}

const TROPICAL_BIOMES: readonly Biome[] = ['tropical_rainforest', 'tropical_seasonal_forest', 'savanna', 'mangrove'];
const COOL_BIOMES: readonly Biome[] = ['temperate_deciduous_forest', 'temperate_rainforest', 'temperate_grassland', 'boreal_forest', 'tundra', 'alpine', 'steppe', 'cold_desert'];

/**
 * Thermal gate for climate-agnostic biomes (wetland): species that only occur in tropical biomes need a frost-free
 * year (coldest month ≥ 12 °C); species that only occur in cool biomes need a real winter (coldest month ≤ 15 °C).
 * Species listed in both groups, or when no temperatures are known, always pass.
 */
export function speciesThermallyOk(s: Species, monthlyTempC: readonly number[]): boolean {
  if (monthlyTempC.length !== 12) return true;
  const coldest = Math.min(...monthlyTempC);
  const tropical = TROPICAL_BIOMES.some((b) => (s.biomes[b] ?? 0) > 0);
  const cool = COOL_BIOMES.some((b) => (s.biomes[b] ?? 0) > 0);
  if (tropical && !cool) return coldest >= 12;
  if (cool && !tropical) return coldest <= 15;
  return true;
}

/** Biomes that carry a species library (everything in BIOME_INFO except open water and ice sheets). */
export const VEGETATED_BIOMES: readonly Biome[] = (Object.keys(BIOME_INFO) as Biome[]).filter((b) => b !== 'ocean' && b !== 'lake' && b !== 'ice_sheet');
